# Generated by Django 3.2.6 on 2021-09-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sample', models.BooleanField(default=False)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
        migrations.RemoveField(
            model_name='sampletestcase',
            name='problem_id',
        ),
        migrations.DeleteModel(
            name='HiddenTestCase',
        ),
        migrations.DeleteModel(
            name='SampleTestCase',
        ),
    ]
