# Generated by Django 3.2.6 on 2021-08-30 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20210830_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddentestcase',
            name='hidden_testcases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
        migrations.AlterField(
            model_name='hiddentestcase',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hiddentestcase',
            name='output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sampletestcase',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sampletestcase',
            name='output',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sampletestcase',
            name='sample_testcases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
    ]
