# Generated by Django 3.2.6 on 2021-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problem_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.TextField(default='', help_text='Input format'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.TextField(default='', help_text='Expected output format'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000, help_text='in milliseconds'),
        ),
    ]
