# Generated by Django 3.2.6 on 2021-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210830_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
