# Generated by Django 3.2.6 on 2021-08-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20210830_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiddentestcase',
            old_name='hidden_testcases',
            new_name='problem_id',
        ),
        migrations.RenameField(
            model_name='sampletestcase',
            old_name='sample_testcases',
            new_name='problem_id',
        ),
    ]
