# Generated by Django 3.2.6 on 2021-09-04 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lang', models.IntegerField(choices=[(0, 'C++'), (1, 'Java'), (2, 'Python')], default=1)),
                ('verdict', models.CharField(choices=[('AC', 'accepted'), ('WA', 'wrong answer'), ('TE', 'time limit exceeded'), ('CE', 'compile error'), ('RE', 'runtime error'), ('TT', 'testing')], max_length=2)),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
