# Generated by Django 3.2.6 on 2021-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('GNU G++ 9.3.0', 'g++'), ('GNU GCC 9.3.0', 'gcc'), ('Java 11.0.10', 'java'), ('Python 3.8.10', 'python')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'accepted'), ('WA', 'wrong answer'), ('TE', 'time limit exceeded'), ('CE', 'compile error'), ('RE', 'runtime error'), ('TT', 'testing')], default='TT', max_length=2),
        ),
    ]
