# Generated by Django 3.2.6 on 2021-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210905_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('GNU G++ 9.3.0', 'g++'), ('GNU GCC 9.3.0', 'gcc'), ('Python 3.8.10', 'python')], default=1, max_length=30),
        ),
    ]
