# Generated by Django 3.2.6 on 2021-09-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_submission_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='lang',
            new_name='judge',
        ),
    ]
