# Generated by Django 3.2.13 on 2022-07-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_lang_submission_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='judge',
            field=models.CharField(choices=[(2, 'Python 3.8.10'), (3, 'GNU GCC C11 11.2.0'), (4, 'GNU G++14 11.2.0'), (5, 'GNU G++17 11.2.0'), (6, 'GNU G++20 11.2.0')], max_length=30),
        ),
    ]
